### PR TITLE
ko_kr localization update

### PR DESCRIPTION
**Pull request by mihile**
update ko_kr + small fix

### CODE REVIEW

**Comment by RobertSkalko** [comment]
On stuff like  "mmorpg.stat.plus_lvl_rejuvenate_spells": "+ 회복 주문",
are you sure the + should be there at all? In english the loc is "to x spells", so in the stat tooltip it will show +2 to x spells.
yours will show +2 + 회복 주문

**Comment by mihile** [comment]
is that mean extra spell point? i can't check cause i dont know how to create runewords. when i right click runes, only i can see wiki page

**Comment by RobertSkalko** [comment]
It means it adds a level to certain spells. +2 to fire spells will turn your lvl 10 fireball into a lvl 12 fireball

**Comment by mihile** [comment]
oh! i got it thx! fixed now

**Pull request merged**
