### PR TITLE
Update zh_tw.json

### PR DESCRIPTION
**Pull request by Joeeey0219**
Update to version 5.9.6 available

Since the original version is too old, I made it into a new one

### CODE REVIEW

**Comment by TUsama** [comment]
很多都是从简中那边转过来的。建议你再仔细看看，因为简中里有一些表达在繁中里是不怎么用的。

**Comment by Joeeey0219** [comment]
好，我這幾天找時間再檢查一次
Okay, I'll find time to check again in the next few days.

**Comment by RobertSkalko** [comment]
I think this is outdated now after i merged the other PR

**Comment by Joeeey0219** [comment]
Got it, then I'll close the pull request

**Pull request closed without merging**
