### PR TITLE
update zh-tw translate 

### PR DESCRIPTION
**Pull request by tasi788**
update zh-tw translate files

### CODE REVIEW

**Comment by tasi788** [comment]
Hi @RobertSkalko , despite me pushing an automated CI/CD action to check the validity of JSON, it seems that this repo is not enabled. Please remember to enable it for it to take effect.

**Comment by RobertSkalko** [comment]
Should be enabled now

**Comment by tasi788** [comment]
> Should be enabled now

let me make some commit to try 👌

**Comment by tasi788** [comment]
it works fine 🎉

**Comment by RobertSkalko** [comment]
I'll merge right away because i'll be off for a while possibly

**Pull request merged**
