### PR TITLE
Add japanese localization

### PR DESCRIPTION
**Pull request by ysi831**
It's not perfect, but it should be useful enough for the Japanese 🌝

### CODE REVIEW

**Comment by RobertSkalko** [comment]
Anyone that knows the language you're free to review this, i'll merge in a few days

**Comment by ysi831** [comment]
some improvements

**Comment by ysi831** [comment]
That's all for now.

**Comment by TUsama** [comment]
1. In line 592, you translate Sharpening Stone to "砥石", but in the next line you translate it as "晶石", is it on purpose?
2. I've seen some lines like 1662 stay unchanged, these are all about format. Translators can delete the space or change the placeholder to avoid syntactic problems like unreadable sentence order or weird space. As far as I know, Japanese writing does not commonly use spaces， so I recommend you reconsider it.

**Comment by ysi831** [comment]
Thanks for your comment.
I'm working on this alone, so it's tough to get it perfect.
It started with a machine translation, then I corrected  frequently used terms and phrases.
So, If you could let me know what I should particularly focus on, that would be helpful.

**Comment by ysi831** [comment]
Fixed about 1. Placeholders looks not bad as it is now for me.

**Comment by TUsama** [comment]
lgtm, but I still recommend you find some of your friends to help you review this.

**Comment by RobertSkalko** [comment]
Merging, for any more edits make a new PR

**Pull request merged**
