### PR TITLE
Update zh_cn.json

### PR DESCRIPTION
**Pull request by golddan114**
I have added new content that can be translated, and I will add any incomplete content later
我为新版本的技能组、功能组做了汉化，后续会更新

### CODE REVIEW

**Comment by RobertSkalko** [comment]
Will merge in 5 days if it's all good according to others

**Comment by bg-7** [comment]
This Chinese translation is excellent！

**Comment by golddan114** [comment]
> 这个中文翻译太棒了！

Thank you for your support. We can play and optimize together

**Comment by yt61300** [comment]
lol. More understandable than my own google translation results

**Comment by mars1908** [comment]
It's really good ,I am trying to contact the writer to translate the mod！

**Comment by sober713** [comment]
This translation is so good, the skill name is fantastic

**Comment by Mujier** [comment]
In Bilibili see, the Chinese content is very small, I hope the author can have follow-up optimization

**Comment by golddan114** [comment]
> 在Bilibili上看到，中文内容很少，希望作者可以有后续优化

sure

**Comment by IHtest0** [comment]
Excellent localization file ...... I mean, it really does restore the text content within the mod very well.
Expect subsequent incremental updates on textual Chineseization.
非常好工作，爱来自中国（

**Comment by RobertSkalko** [comment]
Seems god, merging

**Pull request merged**
