### PR TITLE
add github action

### PR DESCRIPTION
**Pull request by tasi788**
I have added a GitHub action that can automatically check the validity of JSON when pushing or creating a pull request.

### CODE REVIEW

**Comment by RobertSkalko** [comment]
Might be useful

Can someone confirm this does what it says? I can't figure out where it actually validates it

**Comment by tasi788** [comment]
> Might be useful
> 
> Can someone confirm this does what it says? I can't figure out where it actually validates it

For example, the existing zh_tw and pt_br are both invalid JSON files, which can be seen here.

JSON does not allow the # symbol
https://github.com/RobertSkalko/Mine-And-Slash-Rework/blob/dcacd7aefb2a39c6e67b9b3bfc761e5df2ae1e4b/src/main/resources/assets/mmorpg/lang/zh_tw.json#L1

and there is a missing comma here (not just in this place)
https://github.com/RobertSkalko/Mine-And-Slash-Rework/blob/dcacd7aefb2a39c6e67b9b3bfc761e5df2ae1e4b/src/main/resources/assets/mmorpg/lang/pt_br.json#L553

**Comment by RobertSkalko** [comment]
Where in the code does it validate it though?

**Comment by tasi788** [comment]
I used jq to implement the validation part, you can refer to it here

https://github.com/tasi788/Mine-And-Slash-Rework/blob/d71e9f0a4811d353f024f90081e2cce987b2da80/.github/workflows/validate-translate.yml#L22-L31

action result

https://github.com/tasi788/Mine-And-Slash-Rework/actions

**Comment by RobertSkalko** [comment]
Yeah but where exactly? `jq empty "$file"` , "empty" doesn't sound like a validation method

**Comment by tasi788** [comment]
> jq empty

It is similar to the concept of curl slient, it will only parse JSON without outputting the result. You can refer to it here: https://jqlang.github.io/jq/manual/#empty

**Comment by RobertSkalko** [comment]
`It's useful on occasion. You'll know if you need it :)`

Well the documentation is really helpful lol. So how do i know if the json ends up broken, will it show an error?

**Comment by tasi788** [comment]
> `It's useful on occasion. You'll know if you need it :)`
> 
> Well the documentation is really helpful lol. So how do i know if the json ends up broken, will it show an error?

exactly.

**Comment by tasi788** [comment]
result will be like below

image

https://github.com/tasi788/Mine-And-Slash-Rework/actions/runs/11830576566/job/32964330327

**Comment by RobertSkalko** [comment]
Alright sounds good

**Pull request merged**
