### PR TITLE
First pass at being able to auto salvage support gems in a fine-grained way

### PR DESCRIPTION
**Pull request by sesgoe**
This is very much a work-in-progress PR -- I am a complete newb to Minecraft modding so this is my second foray into changing behavior in a mod that I like, so please forgive any extremely stupid mistakes -- I will be more than happy to fix whatever I need to here.

@RobertSkalko the last piece I think I need help with is ensuring that `PlayerConfigData` is compatible with older versions of the mod properly, since it seems like that particular file is related to some NBT data that's stored on the player. I also need to make it work seamlessly with the existing GUI, and I have a plan in mind for that, but I wanted to talk about making it backward compatible first before I messed with making it seamless with the GUI.

I refactored a few things for my own preferences, but I don't know how this breaks the auto serialization/deserialization stuff in the `PlayerData.java` file with this line:

```java
this.config = loadOrBlank(PlayerConfigData.class, new PlayerConfigData(), nbt, CONFIG, new PlayerConfigData());
```

I took your advice and implemented this as a set of commands instead of trying to build a new GUI for it. The cool thing is that this enables a new GUI later, but this gets the super-nerd functionality a lot quicker. The intention of a change like this is for end-game content where I broadly want to salvage common/uncommon/rare support gems, but certain ones, like the Greater Cooldown Reduction are powerful even at `Common` rarity, so I'd rather keep those.

Without this change, the current gameplay is to leave ALL gems disabled for auto salvage, and manually sorting them after every map run. In mythic maps, this is 120+ support gems per run, and gets cumbersome, and I also could miss a gem I want and not know it when I'm going fast.

I realize upon writing this draft message that I haven't considered the augment gems (I think you call them Aura gems) properly, so that will probably have to be fixed here too.

This is an initial act of good-faith, let's talk about implementing this and seeing what I can do to get this merged in to make a few players' lives a little more convenient.

Thanks for this absolutely amazing mod, can't even begin to explain how much I'm enjoying playing with it.

### CODE REVIEW

**Comment by RobertSkalko** [comment]
Backwards compatibility isn't that important on things like this. Players at most lose their salvage settings.
But i do keep names short when it's data that's saved with gson.

What i'd change is i'd generify this. There's no reason why this should only work on support gems.
SalvageType: split spell into supp gems and auras. Then probably add a class and a class check against the type string. 

Like GEAR(Words.Gear, stack, type -> if (Stacksaving.GEAR.has(stack) { return StackSaving.GEAR.loadfrom(stack).basegear.guid.equals(type) }

and the salvagetype would also have registry enum for which registry is used to get a list of types.

So gears would be additionallity configurable to salvage or not based on their base gear type, Gems by gem id, and jewels with nothing currently. 

These could later be added to another gui as "extra salvage configs", where each of these specific salvage tweaks is listed as one button and there's a way to delete them by clicking on them maybe

So they'd be saved in another map like hashmap<Salvagetype,map<typeidstring,rarityToSalvage>>

So check if the salvagetype has  custom salvage config, take that, if not, go for the generic one. Maybe gears might want multiple options to configure salvaging but it'd be too complicated and being able to salvage all say shields if you never use shields would be useful enough

**Comment by sesgoe** [comment]
> Backwards compatibility isn't that important on things like this. Players at most lose their salvage settings. But i do keep names short when it's data that's saved with gson.

Fair enough!

> What i'd change is i'd generify this. There's no reason why this should only work on support gems. SalvageType: split spell into supp gems and auras. Then probably add a class and a class check against the type string.
> 
> Like GEAR(Words.Gear, stack, type -> if (Stacksaving.GEAR.has(stack) { return StackSaving.GEAR.loadfrom(stack).basegear.guid.equals(type) }
> 
> and the salvagetype would also have registry enum for which registry is used to get a list of types.
> 
> So gears would be additionallity configurable to salvage or not based on their base gear type, Gems by gem id, and jewels with nothing currently.

I think I see what you're saying here -- basically keep current salvage setup, but optionally configure by gem id / gear type that overrides rarity configurations...instead of the way I've set this up, which is maybe overcomplicated because it goes into gem type + rarity, when really I'm using it to accomplish "don't salvage this gem id, regardless of rarity"

> These could later be added to another gui as "extra salvage configs", where each of these specific salvage tweaks is listed as one button and there's a way to delete them by clicking on them maybe
> 
> So they'd be saved in another map like hashmap<Salvagetype,map<typeidstring,rarityToSalvage>>

Ok, this makes sense to me, and I like this implementation.

> So check if the salvagetype has custom salvage config, take that, if not, go for the generic one. Maybe gears might want multiple options to configure salvaging but it'd be too complicated and being able to salvage all say shields if you never use shields would be useful enough

Agreed, this does seem marginally more useful this way with gear too. Seems like we could call these something like auto salvage overrides that take precedence over the generic configurations.



So in the situation where you have gear other than legendary / mythic marked as auto-salvage, if you have shields set to auto-salvage, mythic + legendary shields would be auto-salvaged, but mythic + legendary other gear would not

**Comment by sesgoe** [comment]
Little demo video of this:
https://drive.google.com/file/d/1KJMy-KPMx48YqfgRzIaEwZAfuaPlijaI/view?usp=sharing

**Comment by RobertSkalko** [comment]
Will try it out and see

**Pull request merged**
