### PR TITLE
add two simple animation

### PR DESCRIPTION
**Pull request by TUsama**

### CODE REVIEW

**Comment by RobertSkalko** [comment]
What does this do exactly

**Comment by TUsama** [comment]
https://github.com/user-attachments/assets/17ac2269-5e58-4327-969a-4c95fff8c36e

two easy animations tho.  The only thing that needs to be considered is whether it might be unusable after the version upgrade.

**Comment by RobertSkalko** [comment]
Corrupt file

**Comment by TUsama** [comment]
see discord

**Pull request merged**
