### PR TITLE
Feat: Localization fix

### PR DESCRIPTION
**Pull request by TUsama**
I have tried to use the method you did in https://github.com/RobertSkalko/Mine-And-Slash-Rework/commit/984284ee6594d04ba53e1781dcbc28d49c622ef5, and it works.

I've tried my best not to break your work process, so I basically make additions(well the Words do not count) instead of changes.

I hope you can give it a review, cuz I do the whole work in VSC with basic syntax highlight. Don't worry, It can be compiled properly, but I still need the skillful to check the code.

### CODE REVIEW

**Comment by TUsama** [comment]
you mean all the additions? or except the Words and Chat.
I tested most of them and they seemed all good.

**Comment by RobertSkalko** [comment]
Just transfer the additions from en.json file to manual.json and the PR should be good

**Comment by RobertSkalko** [comment]
I can just merge and fix it myself if you want, please just respond quick, this PR has a lot of file changes

**Comment by TUsama** [comment]
push another commit here, that does a lot.
please check out the commit message, it describes the change I have done.

**Comment by TUsama** [comment]
ok I didn't receive the email, otherwise, I would just let this PR merge.

**Comment by TUsama** [comment]
OK now its done. If there is still something needs to be changed, you can just fix it by yourself.

**Comment by RobertSkalko** [comment]
Turns out this was not tested, it doesn't work, and I reverted it. Some were simple mistakes like the level and xp on the bar not having inputted the arguments for lvl and exp % but others I don't want to figure out.. If you try to fix this you need to actually test it and make sure it works.

Also, giving things IAutoLocName is not enough, they have to be added to CreateLangFile just like Words enum is.

To test your changes you need to enable RUN_DEV_TOOLS in MMORPG class and run the game, this will generate the automatic en_us.json lang file (for the next run of the game).

So just run the game, look at the gui, the spell tooltips etc, if everything works, then you can PR again if you want

**Pull request merged**
