### PR TITLE
Localization fix

### PR DESCRIPTION
**Pull request by TUsama**
I've tested this time, it looks all good.
In this PR I made some changes you might be concerned about, like the Json escape while exporting the lang. I explain the reason in the commit message, you can check it if you'd like.

### CODE REVIEW

**Comment by RobertSkalko** [comment]
Hm, why does every type of chest implement an override to locNameLangFileGUID() and locNameGroup()   with the same thing? I'd just add that to the base class so no repetition.

And some of the chests seem to use automatic locname from guid with substrings while others have wrong names like "Harvest Purple Chest", i think i just made them all named "loot chest" for simplicity, so just name them all loot chest for now in the base class and that's it.

Seems you removed the curseforge publish stuff from gradle too so you figured out how to test the mod in IDE, but please revert that when you do PRs

**Comment by TUsama** [comment]
that makes sense, now I know why they are all named "loot chest", I just got confused and don't know what trick you use in the loot chest part. I'll remove all the impl.

**Comment by TUsama** [comment]
also do I need to add the station block lang to the manual.json?

**Comment by RobertSkalko** [comment]
You mean give profession stations names? Sure. I forgot to do that

**Comment by TUsama** [comment]
ok I'll leave it to you

**Comment by RobertSkalko** [comment]
I just noticed you added every single loot chest separately to the createlangfile..  Good thing that's reverted now, what i do is addall from the exileDB.

so remove   list.addAll(Arrays.asList(new AscendancyClass()));  too

**Comment by RobertSkalko** [comment]
I'll merge now and test it if you have no more changes you want to do

**Comment by TUsama** [comment]
And I now remember why I add impl for LootChect.java, the chest type is hardcoding.

**Comment by RobertSkalko** [comment]
Ah true, forgot about that unloc tooltip. For now i'll just merge and test this PR while you're still here

**Comment by TUsama** [comment]
OK

**Comment by RobertSkalko** [comment]
Ok, testing. Noticing double spaces in gear stats

**Comment by TUsama** [comment]
I made it for purpose actually, but if you want to change it you can just edit the statnamerex.java

**Comment by RobertSkalko** [comment]
Thanks, yeah it looked off to me. I don't notice any more problems yet. I fixed one case of float problem on the exp % on the gui, made it an integer.

**Comment by RobertSkalko** [comment]
Also how did you turn the icons for element like [calc:black_hole]§5☀ Chaos§7 into [calc:black_hole] \u00A75\u2600 Chaos\u00A77 ? Didn't notice that in the commit but i saw the change in my lang file after it generated. It seems to both work though

**Comment by TUsama** [comment]
yeah I used the escapeJava() to avoid the encoding issue on my PC. you can also rollback it

**Pull request merged**
